spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/meethere?useUnicode=yes&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: Thwf1858
  mail:
    protocol: smtp
    port: 465
    host: smtp.qq.com
    username: 852092786@qq.com
    password: gxntmgkfmqtkbcha
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    from: 852092786@qq.com
  redis:
    host: 152.136.173.30
    password: LAIqian~~666
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
logging:
  level:
    com.rhenium.meethere.dao: debug
